# Generated by Django 2.1 on 2019-12-28 12:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_auto_20191226_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlsMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=100)),
                ('_from', models.CharField(max_length=100)),
                ('method', models.IntegerField(default=-1)),
                ('nonce', models.IntegerField(default=-1)),
                ('value', models.IntegerField(default=-1)),
                ('gas_price', models.IntegerField(default=-1)),
                ('gas_limit', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='EPostProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.CharField(max_length=100)),
                ('PostRand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrf_proof', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='block',
            name='method',
        ),
        migrations.RemoveField(
            model_name='block',
            name='to',
        ),
        migrations.AddField(
            model_name='block',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='block',
            name='height',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block'),
        ),
        migrations.AddField(
            model_name='epostproof',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block'),
        ),
        migrations.AddField(
            model_name='blsmessages',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block'),
        ),
    ]
