# Generated by Django 2.1 on 2019-12-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_auto_20191228_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlsMessages',
            new_name='BlsMessage',
        ),
        migrations.RenameField(
            model_name='epostproof',
            old_name='PostRand',
            new_name='postrand',
        ),
    ]
