# Generated by Django 2.2.9 on 2020-01-06 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_auto_20191229_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='更新时间戳'),
        ),
    ]
