# Generated by Django 2.2.9 on 2020-01-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0006_auto_20200106_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='parent_weight',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ParentStateRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slash', models.CharField(max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block')),
            ],
        ),
        migrations.CreateModel(
            name='ParentMessageReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slash', models.CharField(max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slash', models.CharField(max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slash', models.CharField(max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partial', models.CharField(max_length=100)),
                ('sector_id', models.IntegerField(default=-1)),
                ('challenge_index', models.IntegerField(default=-1)),
                ('parent_weight', models.IntegerField(default=-1)),
                ('epost_proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.EPostProof')),
            ],
        ),
        migrations.CreateModel(
            name='BLSAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block')),
            ],
        ),
        migrations.CreateModel(
            name='BlockSig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=128)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block')),
            ],
        ),
    ]
