# Generated by Django 2.2.9 on 2020-01-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0007_auto_20200107_0938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidates',
            new_name='Candidate',
        ),
    ]
